### ISSUE TITLE
The following tasks did not complete: package, build, , webpack:build

### ISSUE THREAD

**Issue by darnaupont** [olefredrik/FoundationPress#1219] opened 2018-01-27 18:57 UTC
Hi!
When i try to "npm run build" or "npm run package" apears this error to me. I tried also with a clean new version of FoundationPress and the same error happens.
Im pretty sure that's my fault but im not able to fix it.
(I'm a noob)

Thank you

**How can this bug be reproduced?**
- npm start - works perfect
- npm run build - crash as shown
- npm run package - crashes also

**What happened ?**

```
$ npm run build

> foundationpress@2.10.4 build C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress
> gulp build --production

[11:48:26] Requiring external module babel-register
[11:48:28] Loading config file...
[11:48:28] config.yml does not exist, loading config-default.yml
[11:48:28] Using gulpfile C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\gulpfile.babel.js
[11:48:28] Starting 'build'...
[11:48:28] Starting 'clean'...
[11:48:28] Finished 'clean' after 38 ms
[11:48:28] Starting 'sass'...
[11:48:28] Starting 'webpack:build'...
[11:48:28] Starting 'images'...
[11:48:28] Starting 'copy'...
[11:48:29] Finished 'copy' after 869 ms
[11:48:30] gulp-imagemin: Minified 6 images (saved 51.39 kB - 25.9%)
[11:48:30] Finished 'images' after 1.91 s
{ Error
    at new JS_Parse_Error (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2075:25)
    at maybe_conditional (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2834:13)
    at maybe_assign (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2875:20)
    at expr_atom (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2608:26)
    at maybe_unary (eval at <anonymous> (C:\wamp64v3\www\sessitges\wp-content\themes\foundationpress\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2792:19)
  message: 'C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\app.js: Unexpected character \'`\'',
  fileName: 'C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\app.js',
  lineNumber: 105,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1542:11)\n    at parse_error (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1667:9)\n    at Object.next_token [as input] (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1946:9)\n    at next (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2075:25)\n    at maybe_conditional (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2834:13)\n    at maybe_assign (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2856:20)\n    at expression (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2875:20)\n    at expr_atom (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2608:26)\n    at maybe_unary (eval at <anonymous> (C:\\wamp64v3\\www\\sessitges\\wp-content\\themes\\foundationpress\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2792:19)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }
[11:48:30] Version: webpack 3.10.0
 Asset    Size  Chunks                    Chunk Names
app.js  366 kB       0  [emitted]  [big]  app
[11:48:31] Finished 'sass' after 3.68 s
[11:48:32] The following tasks did not complete: build, <parallel>, webpack:build
[11:48:32] Did you forget to signal async completion?

```

**Please List the Following:**
* OS & version: Windows 10 Home - v 1709
* Node version (node -v) [Node v4+ is required] : **v8.9.4**
* FoundationPress version (see line 3 in package.json):    **2.10.4**
* Foundation version (found in `node_modules/foundation-sites/package.json`) : **6.4.3**

**Comment by colin-marshall** [comment] 2018-01-27 21:29
@darnaupont please fill out the issue template so we know what versions of Node/npm you are using.

**Comment by darnaupont** [comment] 2018-01-28 12:05
@colin-marshall I tried it again, in the past everything worked to me but after a format I'm having this troubles.. 
The double backslashes may come from the npm instalation?

**Comment by colin-marshall** [comment] 2018-01-29 09:31
@darnaupont in the error message I see 

```
Unexpected character \'`\''
```

The backtick leads me to believe that gulp-uglify is failing because the JS is not being transpiled to ES5 prior to being run through gulp-uglify.

Can you please do `npm run start` and copy the contents of your `app.js` from the `dist` directory to a pastebin and post the link? Thanks!

**Comment by colin-marshall** [comment] 2018-01-29 15:49
Thanks @darnaupont! My hunch was correct, something is failing during webpack building the is and it’s not transpiling or including all the modules. @conorbarclay any ideas?

**Comment by conorbarclay** [comment] 2018-01-29 17:51
Interesting. I've created a forked `gulpfile.babel.js` which uses Webpack's built-in `UglifyJsPlugin()` rather than `gulp-uglify` to act on the JS. Try it out, and let me know if it works -- if so, maybe we can get a PR together to kill that Gulp plugin in the repo.

https://github.com/conorbarclay/FoundationPress/blob/master/gulpfile.babel.js

**Comment by colin-marshall** [comment] 2018-01-29 18:05
@conorbarclay even though `gulp-uglify` is throwing the error, I don't believe it is the root of the issue. The error is happening because `gulp-uglify` is seeing backticks in ES6 code. The code is supposed to be ES5 by the time it hits `gulp-uglify`.

Something is happening when webpack is bundling. Look at the [pastecbin](https://pastebin.com/6FSfphPg) of his `app.js` when he does `npm run start`, which bypasses `gulp-uglify`. It's only 208 lines. Mine is 12,403 on a clean FP install.

You setup the webpack bundling of JS, which I have little experience in.

**Comment by conorbarclay** [comment] 2018-01-29 18:43
@colin-marshall Ah, you know what -- you're on to something. I think it might be how Windows handles paths/slashes and that it's not catching (and consequently, not transpiling) the `foundation-sites` folder because of it.

From: https://github.com/webpack/webpack/issues/2073#issuecomment-186286504

I don't have a Windows machine available to test this at the moment, but it looks like all that may be involved is adjusting line 108 of `gulpfile.babel.js` from:

    exclude: /node_modules(?!\/foundation-sites)/,

to:

    exclude: /node_modules(?![\\\/]foundation-sites)/,

**Comment by colin-marshall** [comment] 2018-01-29 19:01
@conorbarclay thanks! Sounds like that might be it. From that issue you linked, it looks like we can make that change and it should work across the board (Windows, Mac, Linux, etc.)? 

No Windows machine here either, so @darnaupont will have to test this out.

**Comment by darnaupont** [comment] 2018-01-29 19:06
Hey guys! ASAP i gonna try it(tomorrow), looks like a good solution, I will let you know the results. Thank you!

**Comment by maciekgrzybek** [comment] 2018-01-30 15:44
I've got same issue on iMac, so it doesn't look like a windows-specific thing.

**Comment by darnaupont** [comment] 2018-01-30 16:38
@colin-marshall @conorbarclay No errors now. Either build and package works well. Its solved for me, THANKS fellas!

**Comment by colin-marshall** [comment] 2018-01-30 17:16
@darnaupont great! Also please verify for us that your `app.js` looks complete with about 12,000 lines of code (unminified). Even though `npm run start` was not giving you errors before, the JS was messed up.

@maciekgrzybek interesting. Did you try the fix @conorbarclay suggested?

**Comment by darnaupont** [comment] 2018-01-30 18:36
@colin-marshall https://pastebin.com/vDuwynNd as I said npm run build and package works well, I can import from a wordpress site the clean version(i have troubles with my old edited version, but i will figure out whats wrong, since the clear install works perfect now)

**Comment by maciekgrzybek** [comment] 2018-01-31 09:31
@colin-marshall @conorbarclay tried thatm didn't help unfortunately, any other ideas?

**Comment by colin-marshall** [comment] 2018-01-31 16:02
@maciekgrzybek please paste your error output here.

**Comment by maciekgrzybek** [comment] 2018-01-31 16:14
@colin-marshall 

> [16:13:58] The following tasks did not complete: build, <parallel>, webpack:build
[16:13:58] Did you forget to signal async completion?

**Comment by colin-marshall** [comment] 2018-01-31 16:18
@maciekgrzybek I need the whole output, like the first in this thread. Thanks.

**Comment by maciekgrzybek** [comment] 2018-01-31 16:19
Right, sorry my bad, here it is : 

> [16:17:08] Failed to load external module @babel/register
[16:17:08] Requiring external module babel-register
[16:17:09] Loading config file...
[16:17:09] config.yml does not exist, loading config-default.yml
[16:17:09] Using gulpfile /Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/gulpfile.babel.js
[16:17:09] Starting 'build'...
[16:17:09] Starting 'clean'...
[16:17:09] Finished 'clean' after 8.53 ms
[16:17:09] Starting 'sass'...
[16:17:09] Starting 'webpack:build'...
[16:17:09] Starting 'images'...
[16:17:09] Starting 'copy'...
[16:17:10] Finished 'copy' after 749 ms
[16:17:13] Finished 'sass' after 3.86 s
{ Error
    at new JS_Parse_Error (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
  message: '/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/app.js: SyntaxError: Unexpected token: operator (>)',
  fileName: '/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/app.js',
  lineNumber: 454,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)\n    at js_error(eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)\n    at croak (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)\n    at expr_atom (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)\n    at maybe_unary (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)\n    at expr_ops (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)\n    at maybe_conditional (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)\n    at maybe_assign (eval at <anonymous> (/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }
[16:17:13] Version: webpack 3.10.0
 Asset    Size  Chunks                    Chunk Names
app.js  368 kB       0  [emitted]  [big]  app
[16:17:13] gulp-imagemin: Minified 3 images (saved 11.52 kB - 1.7%)
[16:17:13] Finished 'images' after 4.42 s
[16:17:14] The following tasks did not complete: build, <parallel>, webpack:build
[16:17:14] Did you forget to signal async completion?

**Comment by conorbarclay** [comment] 2018-01-31 16:39
What version of Node? And I'm assuming this is a fresh install of the most up-to-date FP?

**Comment by colin-marshall** [comment] 2018-01-31 16:40
@maciekgrzybek thanks. Does this happen for you on a fresh install of FoundationPress? Your error gives the greater than sign as the cause of the error:

```
message: '/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/app.js: SyntaxError: Unexpected token: operator (>)',
fileName: '/Applications/MAMP/htdocs/SITES/woodside-new/wp-content/themes/woodside-square/app.js',
lineNumber: 454,
```

BTW you use backticks to embed code in a comment. See the syntax highlighting section of this page:
https://guides.github.com/features/mastering-markdown/

**Comment by maciekgrzybek** [comment] 2018-02-01 08:49
I downloaded FP about 1.5 week ago, when I started to build the website. I've changed gulpfile.babel.js to the one from repo, also I removed node_modules and reinstall them, still got the same error. I'm trying tot rack that unexpected operator, but no luck so far.

**Comment by maciekgrzybek** [comment] 2018-02-01 09:32
Turns out, you cannot import Swiper the ES6 way, needed to enque script from CDN. Thanks for help everyone!

**Comment by colin-marshall** [comment] 2018-02-01 16:29
Glad you got it working!

**Comment by pixelbrad** [comment] 2018-02-16 23:25
Hey guys,

Just ran into this issue myself - applied the fix mentioned above and all is well. 

Is this fix going to be implemented into the codebase in future releases? I'm curious because FP is typically my go-to when spinning up a WP project, and I work only on Windows. 

Cheers

**Comment by colin-marshall** [comment] 2018-02-17 07:32
@pixelbrad I guess I mistakenly closed this out prematurely. I planned to test it on Mac and then do a PR.

**Comment by JPOak** [comment] 2018-02-22 00:32
@colin-marshall I was just double checking if I could use FP on a windows machine if I had to.  Connected to this, there is still the interchange images bug mentioned here: #1202 . @conorbarclay fork as well as the change to the exclude path seemed to fix it and FP ran smoothly on Windows with no errors for me. Without them, Windows was a no go for me.

**Comment by pcross1986** [comment] 2018-03-15 06:34
> exclude: /node_modules(?!\/foundation-sites)/,

to:

exclude: /node_modules(?![\\\/]foundation-sites)/,

**Closed** 2018-03-22 18:10 UTC

**Comment by dmcgrew** [comment] 2018-08-21 14:34
I'm having this same problem. Not really sure what is going on. Running latest version of FP. https://pastebin.com/6dwDBVUi

Not really sure what is going wrong here. I have a feeling its related to the same things noted above.

**Comment by colin-marshall** [comment] 2018-08-21 15:09
@dmcgrew does this happen on fresh clone/install?

**Comment by carldearygithub** [comment] 2018-09-11 12:29
Good Day!

New to this so please don't burn me at the stake! I have tried to supply as much information as i possible could.

Running into issues with FoundationPress when trying to npm run build / npm run package. This was a clean installation with no errors in the beginning of August. 

Node Version: v10.7.0

I have also checked the gulpfile.babel.js file at line 108 and it does show the change from #conorbarclay.

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundationpress@2.10.4~prestart: foundationpress@2.10.4
6 info lifecycle foundationpress@2.10.4~start: foundationpress@2.10.4
7 verbose lifecycle foundationpress@2.10.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle foundationpress@2.10.4~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\websites\summerplace.co.za\wordpress\wp-content\themes\FoundationPress\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Users\Carl\AppData\Local\Microsoft\WindowsApps;C:\Users\Carl\AppData\Roaming\npm;C:\Users\Carl\AppData\Local\GitHubDesktop\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle foundationpress@2.10.4~start: CWD: C:\xampp\htdocs\websites\summerplace.co.za\wordpress\wp-content\themes\FoundationPress
10 silly lifecycle foundationpress@2.10.4~start: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle foundationpress@2.10.4~start: Returned: code: 1  signal: null
12 info lifecycle foundationpress@2.10.4~start: Failed to exec start script
13 verbose stack Error: foundationpress@2.10.4 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid foundationpress@2.10.4
15 verbose cwd C:\xampp\htdocs\websites\summerplace.co.za\wordpress\wp-content\themes\FoundationPress
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.7.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error foundationpress@2.10.4 start: `gulp`
22 error Exit status 1
23 error Failed at the foundationpress@2.10.4 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by carldearygithub** [comment] 2018-09-11 12:31
Just to add onto the above - clean installation of FP does not give issues. Just concerned that this is going to happen as I start working on that clean installation!

**Comment by seppeclijsters** [comment] 2018-11-04 15:15
> Turns out, you cannot import Swiper the ES6 way, needed to enque script from CDN. Thanks for help everyone!

Thanks! Swiper was also my problem...
`import Swiper from 'swiper/dist/js/swiper.js';` did the fix.
