### ISSUE TITLE
Navigation dropdown always open

### ISSUE THREAD

**Issue by roby94** [olefredrik/FoundationPress#783] opened 2016-03-28 19:11 UTC
Hi there,

I'm using FoundationPress for a while, but now i've got a strange issue for the first time.
With the default navigation menu, if there is a submenu, it is always open, while usually it open on hover.

Looking at the code, i've seen that in submenu ul tag there is aria-hidden="true", but id doesn't work.
Look at the screenshot for more information. 

Sorry for bad english.
<img width="1544" alt="schermata 2016-03-28 alle 21 09 24" src="https://cloud.githubusercontent.com/assets/12794151/14087358/ee17d438-f529-11e5-9dbd-fd3bc7d6691d.png">

**Comment by roby94** [comment] 2016-03-30 20:00
I've try to replace original sass code (global/navigation) and original code for topbar, but stil not work.
I'm the only one who had this problem?

**Comment by HRoger** [comment] 2016-03-30 21:19
Hi there. I have the same problem as you too. It seems to be an issue relate to the FLEX BOX.
It appears when you activate it in foundation.scss file:
$global-flexbox : true;

If you set to false the problem is solved, but you can't use flexbox anymore.

**Comment by colin-marshall** [comment] 2016-03-31 01:04
This is a Foundation bug that should be resolved in 6.2.1 with the solution @HRoger has posted. See: https://github.com/zurb/foundation-sites/issues/8278. 6.2.1 will be out very soon so I'll wait until that is finalized before fixing it in FoundationPress.

**Comment by HRoger** [comment] 2016-03-31 01:30
Thank  you!

**Comment by roby94** [comment] 2016-03-31 18:38
Thank you @colin-marshall and @HRoger, your solution works perfectly.

**Comment by rachelreveley** [comment] 2016-05-05 10:21
I think Foundation may have fixed this now. I didn't have the problem in my normal Foundation project but now I am building a WP version of our site and the above solved my troubles.

**Closed** 2017-05-10 12:45 UTC
