### ISSUE TITLE
disable off-canvas menu

### ISSUE THREAD

**Issue by annrie** [olefredrik/FoundationPress#930] opened 2016-12-26 16:40 UTC
**How can this bug be reproduced?**

1. Step one
update v2.8 to v.2.9
2. Step two
3. Step three

**What did you expect to happen?**
Off-canvas menu is not displayed. The menu(links) seems to be displayed, but it seems to be the same color as the background color and it disappears.
I tried various css (.off-canvas, .menu> li> a etc.), but it has no effect at all.
<div class = "off-canvas-wrapper">
<div class = "off-canvas-wrapper-inner" data-off-canvas-wrapper>
I tried it with and without it too.
The code is the same as v 2.8.
Where should I change?

**Please List the Following:**
* OS & version: macOS Sierra
* Node version (node -v) [Node v4+ is required] :
The request is satisfied.
* Foundation version (bower list) :
v6.3

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by linuxbastard** [comment] 2017-08-08 02:28
Hi, I know it's been a while, are you still experiencing the same issue?

Did you update to the newest version of FP? If not, can you try it with the new version and tell us if you still have the same issue? Thanks!

**Comment by olefredrik** [comment] 2017-08-10 08:47
@annrie 

Unable to reproduce your error. The off-canvas menu is properly displayed on my dev environment. Your CodePen links are empty, so I can't verify the issue remotely. If you're still experiencing problems, please have a look in the devtools console and see if it throws any errors. Might be an issue with javascript not loading correctly on your setup. I will close this issue. Please reopen if this is still an issue on your end.

**Closed by olefredrik** 2017-08-10 08:47 UTC
