### ISSUE TITLE
Error with "npm run watch"

### ISSUE THREAD

**Issue by bekircem** [olefredrik/FoundationPress#399] opened 2015-08-02 16:49 UTC
Hi,

I have problem with "npm run watch" command. Here is the screenshot:

http://prntscr.com/7zztyd

Edit: It my mistake. It fixed. Thanks. :)

**Comment by olefredrik** [comment] 2015-08-02 17:39
Not quite sure what's going on here, as you didn't attach the debug log. But you could try ```npm rebuild node-sass``` .

**Comment by olefredrik** [comment] 2015-08-02 18:20
There have been a known issue with ```npm grunt build```. The issue is now fixed. See this thread for details: https://github.com/olefredrik/FoundationPress/issues/386

And, of course, you will need to run a ```npm install``` before you can build or watch.

**Closed** 2015-08-05 12:25 UTC
