### ISSUE TITLE
Deprecation warning... And BrowserSync

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#1277] opened 2018-05-31 15:43 UTC
Not an error, just it seems thing are moving forward faster than I think! I got this with last FoundationPress
`DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("spin")) instead.`

Also, it's been 3 month since I worked with Foundation. I see that in the new version, Browsersync is back to the code you have to add in the footer. The last version I use was opening auto a Browser window.
Just for my information, why choose a version or another. (I prefer the actual version where you have to add a small code, you just have to not forgot to remove it before production!).

**Comment by dantahoua** [comment] 2018-05-31 19:20
Forget about BrowserSync, I never made the link between the fact that when you enter your local dev url in the config.yml, BrowserSync launch your browser... I'm tired today...

**Comment by colin-marshall** [comment] 2018-06-06 20:11
@dantahoua what command did you run that showed the deprecation warning? I'm not seeing it on the master branch from `npm i` or `npm start`.

**Comment by dantahoua** [comment] 2018-06-07 13:21
I use nvm... So for this one I'm using node v8.11.2 (npm v6.1.0)
As usual I use npm start... It's just a notice... But I thought it was interesting to share it just in case.
Funny because I have another project I installed one month before and I have no Deprecated notice (same npm/node version but older project, one month older... :) )

**Comment by colin-marshall** [comment] 2018-07-25 18:37
@dantahoua I cannot reproduce on that version of node. I was running npm 6.2.0 but I'm not sure if that makes a difference. If you `rm -rf node_modules` and reinstall does it still show up after running `npm start`?

**Comment by dantahoua** [comment] 2018-07-25 19:09
Nope, it's only on one project... Last one I started one week ago do not have this warning...

**Comment by colin-marshall** [comment] 2018-07-26 01:40
Thanks for the quick response. I'll close this one out then since at worst it's a deprecation warning which has no effect on whether or not the gulp task works.

**Closed** 2018-07-26 01:42 UTC
