### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by tomhermans** [olefredrik/FoundationPress#1167] opened 2017-11-24 10:05 UTC
Uncaught SyntaxError: Unexpected token import #1167 in app.js

import $ from 'jquery';

**How can this bug be reproduced?**

1. Step one
load the page with FoundationPress activated
2. Step two
check console.
3. Step three
mobile menu for instance doesn't work

**What did you expect to happen?**
that JS gets compiled correctly

**What happened instead?**
error on line 1

**Please List the Following:**
* OS & version:
Mac OSX 10.11.6
* Node version (node -v) [Node v4+ is required] :
node 5.6
* FoundationPress version (see line 3 in package.json):
  "version": "2.10.4",

* Foundation version (found in `node_modules/foundation-sites/package.json`) :
      "foundation-sites@6.4.3",

**Comment by colin-marshall** [comment] 2017-11-24 18:53
@tomhermans does jquery exist in `node_modules/jquery`? Were there any errors on `npm install`?

**Comment by tomhermans** [comment] 2017-11-25 22:21
Yes. checked the folder and even re-done npm install. no messages

**Comment by colin-marshall** [comment] 2017-11-26 21:40
@tomhermans I can't reproduce on the same version of node and I'm on the exact same version of macOS. Just to make sure, did you build the theme assets with `npm run start`?

**Comment by colin-marshall** [comment] 2017-12-15 03:00
@tomhermans any update on this issue?

**Comment by tomhermans** [comment] 2018-01-03 18:58
I started over with a fresh FoundationPress and issue is gone. Not really a clue what has changed though..

**Comment by colin-marshall** [comment] 2018-01-03 21:17
@tomhermans that's great! We updated the packages for webpack and babel-loader and also optimized the javascript build/watch tasks in #1169 and #1196. I'm guessing one of these updates were what resolved your issue. Closing this out.

**Closed by colin-marshall** 2018-01-03 21:17 UTC
Labels: awaiting reply
