### ISSUE TITLE
Console error: Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by aibrean** [olefredrik/FoundationPress#1051] opened 2017-08-25 13:58 UTC
I have the compiled js file from the latest FoundationPress running and I get Uncaught SyntaxError: Unexpected token import. This is referencing the following line:
`import $ from 'jquery';`

**Comment by olefredrik** [comment] 2017-08-27 11:24
Did this happen on a fresh install, or after you downgraded the jQuery version (ref https://github.com/olefredrik/FoundationPress/issues/1052)?

**Comment by olefredrik** [comment] 2017-08-30 10:28
I will assume that this issue is due to issue https://github.com/olefredrik/FoundationPress/issues/1052 . I will therefore close this. Feel free to reopen if you think the problem is not related to the other issue.

**Closed by olefredrik** 2017-08-30 10:28 UTC
Labels: need more info

**Comment by aibrean** [comment] 2017-08-31 15:49
This was a fresh install
