### ISSUE TITLE
Where did the npm package into the archive?

### ISSUE THREAD

**Issue by MrAndreius** [olefredrik/FoundationPress#1090] opened 2017-09-24 15:34 UTC
gulp.task  package not found or .....

**Comment by colin-marshall** [comment] 2017-09-25 18:47
Looks like we forgot to port the task over to the new gulpfile. Thanks for letting us know!

**Comment by nitrokevin** [comment] 2017-09-25 19:28
I think ole said it wasn’t reliable in another post, but I miss it a lot personally :)

**Comment by colin-marshall** [comment] 2017-09-25 19:49
Ahhh yes, it is a duplicate of #1042.

@olefredrik (or anybody else) can you tell me what specifically was not working with the package task?

**Comment by MrAndreius** [comment] 2017-09-25 21:11
I have everything worked perfectly
it was so convenient to pack

**Comment by olefredrik** [comment] 2017-10-01 20:36
If you got it working, feel free to bring it back in.

**Comment by olefredrik** [comment] 2017-10-12 11:44
@colin-marshall There have been problems with infinite loops causing huge zip-files. 

> Just wanted to add to this that it's not really the folder, but just the .zip file that needs to be deleted. I made the mistake of creating a package once and then went to lunch and came back with a 400GB+ file, that pretty much crashed my desktop using all available space ;)

https://github.com/olefredrik/FoundationPress/issues/538#issuecomment-161163468

I just usually delete the existing zip, then run it.

There have also been issues with ``npm run package`` not being compatible with different versions of Node. It always worked for me, but after receiving e-mails, github issues, and forum posts about the package script not working as expected, I decided to just remove it. 

That said, I made a mistake just removing the packaging feature without further notice. In the spirit of open source I should have asked the community first. If anyone wants to bring it back in, pull requests are always welcome.

**Comment by colin-marshall** [comment] 2017-10-12 17:33
@olefredrik #538 dealt with grunt so it is unrelated to the gulp package task that was removed. I rewrote it for gulp in https://github.com/olefredrik/FoundationPress/commit/4811705690c673f959145f4d46bce32f0a5bbf20

I'm down to bring it back in, but would like to read up on the node version issues first. I'll see if I can find anything in a search...

**Comment by colin-marshall** [comment] 2017-10-12 17:59
@olefredrik I just searched all issues for the word "package" sorted chronologically from newest to oldest and could not find any issues, resolved or unresolved, relating to problems with the gulp package task. All problems seems to have been with grunt.

I think it's safe for us to add it back in.

**Closed** 2017-10-15 10:09 UTC
Labels: Hacktoberfest
