### ISSUE TITLE
Mobile (hamburger) navigation not responding.

### ISSUE THREAD

**Issue by gbrl** [olefredrik/FoundationPress#951] opened 2017-03-07 17:00 UTC
**How can this bug be reproduced?**

0. Install theme.
1. Create a few pages and publish them.
2. Create a menu with a couple pages (Appearance > Menus > "Create a new menu")
3. Assign the menu to both "Right Top Bar" and "Mobile" positions.
4. Load website on mobile, click on Hamburger, nothing happens.

**What did you expect to happen?**

Load website on mobile, click on Hamburger, menu drops down.

**What happened instead?**

Load website on mobile, click on Hamburger, nothing happens.

**Please List the Following:**

Mac OS Sierra & iOS (latest versions)

Node version: 7.3.0

Bower: 
├── fontawesome#4.5.0 (latest is 4.7.0)
├─┬ foundation-sites#6.3.1
│ ├── jquery#2.2.4 (3.1.1 available)
│ └── what-input#4.0.6 (latest is 4.1.1)
└─┬ motion-ui#1.2.2
  └── jquery#2.2.4 (latest is 3.1.1)

**Include Test Case** (won't be online for very long):  
http://foamandthunder.com

**Comment by EricRihlmann** [comment] 2017-03-11 23:47
In your example there aren't any mobile menu items in the HTML. Can you post a screenshot of **Menu->Manage Locations** tab in WP?

**Comment by bethanyiam** [comment] 2017-03-13 20:35
This same thing is happening to me.

**Comment by bethanyiam** [comment] 2017-03-13 20:37
![screen shot 2017-03-13 at 3 37 03 pm](https://cloud.githubusercontent.com/assets/10352488/23874271/f4695f22-0802-11e7-8bc6-3704e4646c03.png)

**Comment by linuxbastard** [comment] 2017-03-14 13:22
Hi Guys, chiming in with a question. Can you guys inspect the page in Chrome in mobile mode and see if you are seeing a JS error?

**Comment by Glenvig** [comment] 2017-03-14 13:32
No JS error on my site, when I inspect it in mobile mode in Chrome

**Comment by gbrl** [comment] 2017-03-14 14:00
No errors on my end either.

**Comment by linuxbastard** [comment] 2017-03-14 15:21
OK. I'm seeing a JS error on the test case @gbrl posted but it may not be related. I can see that even when clicked, mobile navigation still has "display: none" style attached, so I thought it was a JS issue. Toggling the CSS in inspector for the nav, displays the menu.

**Comment by EricRihlmann** [comment] 2017-03-14 15:21
The problem appears to be caused by Foundation 6.3.1. Previously I couldn't recreate the issue in my local development installation of FoundationPress using Foundation 6.3.0, but I see it now after upgrading to 6.3.1. The issue also goes away when downgrading to 6.3.0. I haven't been able to identify the exact commit that is causing the issue, but here is the comparison between 6.3.0 and 6.3.1. 

https://github.com/zurb/foundation-sites/compare/v6.3.0...v6.3.1

**Comment by EricRihlmann** [comment] 2017-03-14 16:52
I created a pull request with a simple solution to the issue. However, it looks like all of the pull requests are held up by an issue caused by an update in the WordPress coding standards. I suggest just making the change in your local repos until the pull request gets merged. 

You can find it here,
https://github.com/olefredrik/FoundationPress/pull/955/commits/7fa7962d724ab12cf210be7620177f718020ab72

**Comment by gbrl** [comment] 2017-03-14 17:18
@EricRihlmann THANK YOU!

**Comment by EricRihlmann** [comment] 2017-03-16 01:01
@gbrl can you close this out?

**Comment by olefredrik** [comment] 2017-03-16 12:01
Fixed https://github.com/olefredrik/FoundationPress/pull/955/commits/7fa7962d724ab12cf210be7620177f718020ab72

**Closed by olefredrik** 2017-03-16 12:01 UTC
