### ISSUE TITLE
syntax error navigation.php on line 131

### ISSUE THREAD

**Issue by bej-soan** [olefredrik/FoundationPress#1035] opened 2017-08-10 15:29 UTC
I am getting this syntax error with the recent vanilla FoundationPress on my live server, localhost works. 

`Parse error: syntax error, unexpected '[' in /home/www/doc/.../.../wp-content/themes/FoundationPress/library/navigation.php on line 131 `

Here's the file and line on github: [navigation.php](https://github.com/olefredrik/FoundationPress/blob/master/library/navigation.php#L131)

I've used this server environment before with other FoundationPress-Versions.

I changed the `[]` in the line to `null` and it works, but I can't say if it's right. 

Server Specs
* PHP Version 5.3.29
* Apache HTTPD 2.2.x
* MySQL 5.1.51

* FoundationPress version: 2.10.2
* Foundation version: : 6.4.1

**Comment by olefredrik** [comment] 2017-08-10 21:53
That's weird, because the [demosite](https://foundationpress.olefredrik.com/) is also a vanilla FoundationPress install based on the latest version, and this does not produce any syntax errors.

Can I have a link to the live site where you get the error, so I can have a look?

**Comment by bej-soan** [comment] 2017-08-11 07:37
Yes you can have a link, but front- and backend are completely broken when FoundationPress is active. So you're only able to see the error. If I change the line, it's working. 

http://breitwieser.pixelfest.de/

**Comment by olefredrik** [comment] 2017-08-11 20:15
@bej-soan : Thanks! I have tried different php versions on my server now, and I'm able to reproduce the server error when using PHP 5.3. I've tested with all available PHP versions, from 5.3 to 7.0, and 5.3 is the only version that produces the error. 

As [PHP 5.3 does only have 0.98% global usage](https://seld.be/notes/php-versions-stats-2017-1-edition), I think we're good. 

Based on this, I don't see this issue as something that needs to be fixed in the master branch. Thanks for reporting the issue 👍

**Closed by olefredrik** 2017-08-11 20:15 UTC
Labels: out of scope
